import LegalPage from "@/components/LegalPage";
import { getServerLocale } from "@/i18n/server";
import { createMetadata } from "@/utils/seo";

export const metadata = createMetadata({ title: "Terms of Use", description: "Read the terms governing use of the Trustence website.", path: "/terms" });

export default async function TermsOfUse() {
  const fa = (await getServerLocale()) === "fa";
  const content = fa ? { title: "شرایط استفاده", updated: "آخرین به‌روزرسانی: ۱۵ آبان ۱۴۰۴", intro: "با استفاده از trust-ence.com، این شرایط را می‌پذیرید. این شرایط تابع قوانین اتحادیه اروپا و قوانین تکمیلی ایرلند به‌عنوان حوزه نمایندگی ما در اتحادیه اروپا است.", sections: [{ title: "۱. پذیرش شرایط", body: "ادامه استفاده از سایت به معنای پذیرش این شرایط و سیاست حریم خصوصی ماست." }, { title: "۲. رفتار کاربر", items: ["هرگونه رفتار غیرقانونی، آسیب‌زا یا آزاردهنده ممنوع است.", "جمع‌آوری خودکار یا استخراج داده بدون رضایت مجاز نیست.", "ایجاد اختلال در عملکرد سایت ممنوع است."] }, { title: "۳. مالکیت فکری", body: "تمام محتوا تحت قوانین حق نشر اتحادیه اروپا محافظت می‌شود و استفاده بدون مجوز ممنوع است." }, { title: "۴. محدودیت مسئولیت", body: "در محدوده مجاز قانون مصرف‌کننده اتحادیه اروپا، مسئول خسارت‌های غیرمستقیم نیستیم. سقف مسئولیت کل ما ۱۰۰ یورو است." }], action: "تماس با بخش حقوقی" } : { title: "Terms of use", updated: "Last updated: November 06, 2025", intro: "By using trust-ence.com, you agree to these Terms, governed by European Union law and supplemented by the laws of Ireland as our EU representative jurisdiction.", sections: [{ title: "1. Acceptance of terms", body: "Continued use of the site constitutes acceptance of these terms and our privacy policy." }, { title: "2. User conduct", items: ["No unlawful, harmful, or abusive behaviour.", "No automated scraping or data mining without consent.", "No interference with site functionality."] }, { title: "3. Intellectual property", body: "All content is protected under EU copyright law. Unauthorised use is prohibited." }, { title: "4. Limitation of liability", body: "To the extent permitted by EU consumer law, we are not liable for indirect damages. Our total liability shall not exceed €100." }], action: "Contact the legal team" };
  return <LegalPage {...content} email="legal@trustenceagency.com" />;
}
