import { FileCheck2, MessagesSquare, ShieldCheck } from "lucide-react";
import { getServerLocale } from "@/i18n/server";

export default async function WhyUS() {
  const locale = await getServerLocale();
  const fa = locale === "fa";
  const copy = fa ? { eyebrow: "پیش از تعهد", title: "یک گفت‌وگوی خوب باید تصمیم را روشن‌تر کند؛ نه اینکه صرفاً چیزی بفروشد.", body: "اگر پروژه برای تیم ما مناسب نباشد، صادقانه می‌گوییم. اگر مناسب باشد، از همان ابتدا درباره دامنه، ریسک‌ها، مسئولیت‌ها و مالکیت شفاف صحبت می‌کنیم.", items: [["محرمانگی و دقت", "اطلاعات، زمینه کسب‌وکار و ایده‌های شما مسئولانه مدیریت می‌شوند."], ["راهنمایی فنی صادقانه", "پیچیدگی غیرضروری اضافه نمی‌کنیم و تصمیم‌ها را با زبان روشن توضیح می‌دهیم."], ["دامنه و مالکیت شفاف", "تحویل‌ها، زمان‌بندی، سورس و مسئولیت هر طرف از ابتدا مشخص می‌شود."]] } : { eyebrow: "Before commitment", title: "A good first conversation should sharpen the decision—not simply sell something.", body: "If the project is not right for our team, we will say so. If it is, we begin with clarity around scope, risks, responsibilities, and ownership.", items: [["Discretion and care", "Your information, business context, and ideas are handled responsibly."], ["Honest technical guidance", "We avoid unnecessary complexity and explain decisions in direct language."], ["Clear scope and ownership", "Deliverables, timing, source, and each party’s responsibilities are defined early."]] };
  const icons = [ShieldCheck, MessagesSquare, FileCheck2];
  return <section className="bg-[#fff8ee] py-20 text-[#07120c] md:py-28"><div className="container"><div className="grid gap-8 md:grid-cols-[1fr_.7fr] md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#245336]">{copy.eyebrow}</p><h2 className="title mt-5 max-w-5xl text-4xl leading-tight md:text-6xl">{copy.title}</h2></div><p className="max-w-xl text-lg leading-8 text-[#173326]/65 md:justify-self-end">{copy.body}</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-[2rem] border border-[#245336]/12 bg-[#245336]/12 md:grid-cols-3">{copy.items.map(([title, body], index) => { const Icon = icons[index]; return <article key={title} className="bg-white/65 p-7 md:p-9"><div className="flex items-center justify-between"><span className="font-mono text-xs text-[#245336]/45">0{index + 1}</span><Icon className="h-7 w-7 stroke-[1.5] text-[#658672]" /></div><h3 className="title mt-9 text-2xl text-[#123d27]">{title}</h3><p className="mt-4 leading-7 text-[#173326]/65">{body}</p></article>; })}</div></div></section>;
}
